### ISSUE TITLE
Some suggestions for your overview page file

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/grad-js-assigment#8]
1. Your overview page file is HUGE! Can you find some ways to modularize it?
2. You use a mix of ES5 & ES6 functions - try to stick to one convention throughout your code!
3. The majority of your variables initialise with let - have a look through and see which ones are actually reassigned to another value. Can you use const instead?

**Comment by AntonioGargaro** [comment]
Made more modular in #12, used ES6 functions and let removed where not needed.
